### Rule Endpoints ###

# Get all rules
GET http://localhost:3000/rules/all

### 

GET http://localhost:3000/rules/1

###

# Create a new rule (at least one property required)
POST http://localhost:3000/rules
Content-Type: application/json

{
  "fromAddress": "0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6",
  "toAddress": "0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b7",
  "value": "1000000000000000000",
  "gasPrice": "20000000000"
}

###

# Create another rule
POST http://localhost:3000/rules
Content-Type: application/json

{
  "fromAddress": "0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b8",
  "nonce": 5,
  "gasLimit": "21000"
}

###

# Update a rule
PUT http://localhost:3000/rules/1
Content-Type: application/json

{
  "value": "5000000000000000000",
  "gasPrice": "25000000000"
}

###

# Delete a rule
DELETE http://localhost:3000/rules/3

###

# Get transactions by rule ID
GET http://localhost:3000/rules/1/transactions

###

### Transaction Endpoints ###

# Get all transactions
GET http://localhost:3000/transactions/all

###

# Get transaction by ID
GET http://localhost:3000/transactions/1

### 


# Batch insert transactions (optimized with bulk operations)
POST http://localhost:3000/transactions/batch
Content-Type: application/json

{
  "transactions": [
    {
      "hash": "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890",
      "to": "0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b8",
      "from": "0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b9",
      "nonce": 2,
      "gasLimit": "21000",
      "gasPrice": "20000000000",
      "value": "500000000000000000",
      "type": 0,
      "ruleIds": [1]
    },
    {
      "hash": "0xfedcba0987654321fedcba0987654321fedcba0987654321fedcba0987654321",
      "to": "0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b0",
      "from": "0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b1",
      "nonce": 3,
      "gasLimit": "21000",
      "gasPrice": "20000000000",
      "value": "750000000000000000",
      "type": 0,
      "ruleIds": [2]
    },
    {
      "hash": "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef",
      "to": "0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b2",
      "from": "0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b3",
      "nonce": 4,
      "gasLimit": "21000",
      "gasPrice": "20000000000",
      "value": "1000000000000000000",
      "type": 0,
      "ruleIds": [1, 2]
    }
  ]
}

### 

# Get transactions by rule ID
GET http://localhost:3000/transactions/rule/1 